path:
  train_path: data/swapped_dataset.csv #data/train.csv # -> Train csv file path
  val_path: data/dev.csv
  dev_path: data/dev.csv
  predict_path: data/test.csv # -> Test csv file path

  checkpoint_path: bagging_checkpoint/ # -> Checkpoint save path
  output_path: src/output # -> Output csv save path
  submission_path: src/output/sample_submission.csv # -> Sample submission csv file path

# List of model names to use.
model:
  # model_name_1: beomi/KcELECTRA-base
  model_name_2: snunlp/KR-ELECTRA-discriminator
  # model_name_3: jhgan/ko-sroberta-multitask
  ensemble_weight: [0.2, 0.2, 0.2, 0.2, 0.2] #[0.3, 0.3, 0.4]

hyperparameters:
  seed: 0
  num_labels: 1
  num_workers: 4
  batch_size: 16
  max_length: 128
  max_epoch: 40
  learning_rate: 1e-5
